services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keepitup
      POSTGRES_USER: keepitup
      POSTGRES_PASSWORD: keepitup
    ports:
      - '5442:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
